servers:
- url: https://image.octoai.cloud
  x-name: ImageGen
paths:
  /generate/ssd:
    post:
      x-fern-sdk-method-name: generateSsd
  /generate/controlnet-sdxl:
    post:
      x-fern-sdk-method-name: generateControlnetSdxl
  /generate/controlnet-sd15:
    post:
      x-fern-sdk-method-name: generateControlnetSd15
  /generate/sdxl:
    post:
      x-fern-sdk-method-name: generateSdxl
  /generate/sd:
    post:
      x-fern-sdk-method-name: generateSd
  /generate/svd:
    post:
      x-fern-sdk-method-name: generateSvd
  # Hide healthcheck
  /healthcheck:
    get:
      x-fern-ignore: true
