servers:
- url: https://image.octoai.cloud
  x-name: ImageGen
paths:
  /generate/ssd:
    post:
      x-fern-sdk-method-name: generateSsd
      servers:
      - url: ImageGen
  /generate/controlnet-sdxl:
    post:
      x-fern-sdk-method-name: generateControlnetSdxl
      servers:
      - url: ImageGen
  /generate/controlnet-sd15:
    post:
      x-fern-sdk-method-name: generateControlnetSd15
      servers:
      - url: ImageGen
  /generate/sdxl:
    post:
      x-fern-sdk-method-name: generateSdxl
      servers:
      - url: ImageGen
  /generate/sd:
    post:
      x-fern-sdk-method-name: generateSd
      servers:
      - url: ImageGen
  /generate/svd:
    post:
      x-fern-sdk-method-name: generateSvd
      servers:
      - url: ImageGen
  # Hide healthcheck
  /healthcheck:
    get:
      x-fern-ignore: true
