servers:
- url: https://api.octoai.cloud
  description: Production
  x-name: Production
  x-fern-server-name: Default
- url: https://api.securelink.octo.ai
  x-name: Default
  x-fern-server-name: SecureLink
paths:
  # Hide healthcheck
  /health:
    get:
      x-fern-ignore: true
  /v1/tune:
    post:
      x-fern-sdk-method-name: create
  /v1/tune/{tune_id}:
    get:
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-method-name: delete
  /v1/tune/{tune_id}/cancel:
    post:
      x-fern-sdk-method-name: cancel
  /v1/tunes:
    get:
      x-fern-sdk-method-name: list
components:
  schemas:
    LoraTune-Input:
      x-fern-type-name: LoraTune
    LoraTune-Output:
      x-fern-type-name: LoraTune
    Tune:
      x-fern-type-name: Tune
      properties:
        details:
          x-fern-type-name: TuneDetails
