servers:
- url: https://text.octoai.run
  x-name: TextGen
  x-fern-server-name: Production
- url: https://text.securelink.octo.ai
  description: SecureLink
  x-name: TextGen
  x-fern-server-name: SecureLink
paths:
  /v1/chat/completions:
    post:
      x-fern-sdk-method-name: createChatCompletion
      x-fern-streaming:
        stream-condition: $request.stream
        format: sse
        response:
          $ref: "#/components/schemas/ChatCompletionResponse"
        response-stream:
          $ref: "#/components/schemas/ChatCompletionChunk"
  /v1/completions:
    post:
      x-fern-sdk-method-name: createCompletion
      x-fern-streaming:
        stream-condition: $request.stream
        format: sse
        response:
          $ref: "#/components/schemas/CompletionResponse"
        response-stream:
          $ref: "#/components/schemas/CompletionResponse"
